CREATE SCHEMA FRIDGEZONE;
CREATE TABLE item(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    create_by VARCHAR(25),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    stock_level VARCHAR(15) NOT NULL,
    optimal_quantity INT DEFAULT 0 NOT NULL
);
