CREATE SCHEMA FRIDGEZONE;
CREATE TABLE item(
ID INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(255) NOT NULL,
  QUANTITY DECIMAL(6,2) NOT NULL,
    UNITS VARCHAR(15) NOT NULL,
  create_by VARCHAR(25),
   create_date TIMESTAMP default CURRENT_TIMESTAMP
   );