INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity)VALUES(1, 'Pop', 'Out', 2)
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity)VALUES(2, 'Ham', 'Low', 1)
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity)VALUES(3, 'Cheese', 'Low', 2)
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity)VALUES(4, 'Milk', 'Stocked', 1)
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity)VALUES(5, 'Eggs', 'Surplus', 2)