INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(1, 'Pop', 'Out', 2, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(2, 'Ham', 'Low', 1, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(3, 'Cheese', 'Low', 2, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(4, 'Milk', 'Stocked', 1, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(5, 'Eggs', 'Surplus', 2, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(6, 'Oranges', 'Surplus', 2, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(7, 'Pineapples', 'Surplus', 2, 'testUser1')
INSERT INTO ITEM(ID, NAME, stock_level, optimal_quantity, username)VALUES(8, 'Private item!!!', 'Surplus', 2, 'testUser2')

INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(1, 'favorite', 2)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(2, 'favorite', 4)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(3, 'dairy', 4)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(4, 'snacks', 6)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(5, 'fruit', 6)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(6, 'fruit', 7)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(7, 'shopping', 7)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(8, 'favorite', 7)
INSERT INTO TAG(ID, NAME, ITEM_ID)VALUES(9, 'private', 8)


